apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # We are not reachable directly from outside world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
