apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sharank10/kub-demo-frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
