apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: users
  template:
    metadata:
      labels:
        app: users
    spec: 
      containers:
        - name: users
          image: sharank10/kub-demo-users
          env:
            - name: AUTH_ADDRESS
              value: localhost
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: auth
          image: sharank10/kub-demo-auth
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"